version: "2"
run:
  allow-parallel-runners: true
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

linters:
  enable:
    - errcheck
    - asciicheck
    - bodyclose
    - bidichk
    - nilerr
    - perfsprint
    - unconvert
    - whitespace