services:
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - function-logs:/root/functions/logs
    ports:
      - "50051:50051"
    networks:
      - hyperfaas-network
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
  leaf:
    build:
      context: .
      dockerfile: leaf.Dockerfile
    ports:
      - "50050:50050"
    networks:
        - hyperfaas-network
    develop:
        watch:
            - action: rebuild
              path: .
              target: .
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - hyperfaas-network

volumes:
  function-logs:
    name: function-logs

networks:
  hyperfaas-network:
    name: hyperfaas-network
    driver: bridge