[package]
name = "hyperfaas-function-runtime"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
http-body-util = "0.1"
hyper = { version = "1.8", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
prost = "0.13"
tokio = { version = "1.48", features = ["macros", "net", "rt-multi-thread"] }
tonic = "0.13"

[build-dependencies]
tonic-build = "0.13"
