// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	core "hyperfaas-ideal-arch/pkg/core"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_PrepareImage_FullMethodName       = "/hyperfaas.SandboxService/PrepareImage"
	SandboxService_CreateSandbox_FullMethodName      = "/hyperfaas.SandboxService/CreateSandbox"
	SandboxService_StopSandbox_FullMethodName        = "/hyperfaas.SandboxService/StopSandbox"
	SandboxService_ListSandboxes_FullMethodName      = "/hyperfaas.SandboxService/ListSandboxes"
	SandboxService_SignalReady_FullMethodName        = "/hyperfaas.SandboxService/SignalReady"
	SandboxService_CurrentState_FullMethodName       = "/hyperfaas.SandboxService/CurrentState"
	SandboxService_WatchState_FullMethodName         = "/hyperfaas.SandboxService/WatchState"
	SandboxService_WatchSandboxEvents_FullMethodName = "/hyperfaas.SandboxService/WatchSandboxEvents"
	SandboxService_SetLoadOverride_FullMethodName    = "/hyperfaas.SandboxService/SetLoadOverride"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	PrepareImage(ctx context.Context, in *PrepareImageRequest, opts ...grpc.CallOption) (*core.PreparedArtifact, error)
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*core.InstanceState, error)
	StopSandbox(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*StopSandboxResponse, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	SignalReady(ctx context.Context, in *SignalReadyRequest, opts ...grpc.CallOption) (*SignalReadyResponse, error)
	// Diagnostic full snapshot of one worker. It is ungated and not used by the
	// placement path; placement uses WatchState with an explicit projection.
	CurrentState(ctx context.Context, in *CurrentWorkerStateRequest, opts ...grpc.CallOption) (*core.WorkerState, error)
	WatchState(ctx context.Context, in *WatchWorkerStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[core.WorkerState], error)
	// Streams sandbox removal deltas. WatchState is the periodic revisioned
	// relist; WatchSandboxEvents carries the low-latency eviction fast path.
	WatchSandboxEvents(ctx context.Context, in *WatchSandboxEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[core.SandboxRemoved], error)
	// Test/debug override for CH-BL DST. Production invokers do not call this.
	SetLoadOverride(ctx context.Context, in *SetLoadOverrideRequest, opts ...grpc.CallOption) (*SetLoadOverrideResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) PrepareImage(ctx context.Context, in *PrepareImageRequest, opts ...grpc.CallOption) (*core.PreparedArtifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.PreparedArtifact)
	err := c.cc.Invoke(ctx, SandboxService_PrepareImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*core.InstanceState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.InstanceState)
	err := c.cc.Invoke(ctx, SandboxService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StopSandbox(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*StopSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_StopSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SignalReady(ctx context.Context, in *SignalReadyRequest, opts ...grpc.CallOption) (*SignalReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalReadyResponse)
	err := c.cc.Invoke(ctx, SandboxService_SignalReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CurrentState(ctx context.Context, in *CurrentWorkerStateRequest, opts ...grpc.CallOption) (*core.WorkerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.WorkerState)
	err := c.cc.Invoke(ctx, SandboxService_CurrentState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) WatchState(ctx context.Context, in *WatchWorkerStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[core.WorkerState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[0], SandboxService_WatchState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchWorkerStateRequest, core.WorkerState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_WatchStateClient = grpc.ServerStreamingClient[core.WorkerState]

func (c *sandboxServiceClient) WatchSandboxEvents(ctx context.Context, in *WatchSandboxEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[core.SandboxRemoved], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[1], SandboxService_WatchSandboxEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSandboxEventsRequest, core.SandboxRemoved]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_WatchSandboxEventsClient = grpc.ServerStreamingClient[core.SandboxRemoved]

func (c *sandboxServiceClient) SetLoadOverride(ctx context.Context, in *SetLoadOverrideRequest, opts ...grpc.CallOption) (*SetLoadOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoadOverrideResponse)
	err := c.cc.Invoke(ctx, SandboxService_SetLoadOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
type SandboxServiceServer interface {
	PrepareImage(context.Context, *PrepareImageRequest) (*core.PreparedArtifact, error)
	CreateSandbox(context.Context, *CreateSandboxRequest) (*core.InstanceState, error)
	StopSandbox(context.Context, *StopSandboxRequest) (*StopSandboxResponse, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	SignalReady(context.Context, *SignalReadyRequest) (*SignalReadyResponse, error)
	// Diagnostic full snapshot of one worker. It is ungated and not used by the
	// placement path; placement uses WatchState with an explicit projection.
	CurrentState(context.Context, *CurrentWorkerStateRequest) (*core.WorkerState, error)
	WatchState(*WatchWorkerStateRequest, grpc.ServerStreamingServer[core.WorkerState]) error
	// Streams sandbox removal deltas. WatchState is the periodic revisioned
	// relist; WatchSandboxEvents carries the low-latency eviction fast path.
	WatchSandboxEvents(*WatchSandboxEventsRequest, grpc.ServerStreamingServer[core.SandboxRemoved]) error
	// Test/debug override for CH-BL DST. Production invokers do not call this.
	SetLoadOverride(context.Context, *SetLoadOverrideRequest) (*SetLoadOverrideResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) PrepareImage(context.Context, *PrepareImageRequest) (*core.PreparedArtifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareImage not implemented")
}
func (UnimplementedSandboxServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*core.InstanceState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) StopSandbox(context.Context, *StopSandboxRequest) (*StopSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedSandboxServiceServer) SignalReady(context.Context, *SignalReadyRequest) (*SignalReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalReady not implemented")
}
func (UnimplementedSandboxServiceServer) CurrentState(context.Context, *CurrentWorkerStateRequest) (*core.WorkerState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentState not implemented")
}
func (UnimplementedSandboxServiceServer) WatchState(*WatchWorkerStateRequest, grpc.ServerStreamingServer[core.WorkerState]) error {
	return status.Errorf(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedSandboxServiceServer) WatchSandboxEvents(*WatchSandboxEventsRequest, grpc.ServerStreamingServer[core.SandboxRemoved]) error {
	return status.Errorf(codes.Unimplemented, "method WatchSandboxEvents not implemented")
}
func (UnimplementedSandboxServiceServer) SetLoadOverride(context.Context, *SetLoadOverrideRequest) (*SetLoadOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLoadOverride not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_PrepareImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).PrepareImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_PrepareImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).PrepareImage(ctx, req.(*PrepareImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StopSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).StopSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_StopSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).StopSandbox(ctx, req.(*StopSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SignalReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SignalReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SignalReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SignalReady(ctx, req.(*SignalReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CurrentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentWorkerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CurrentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CurrentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CurrentState(ctx, req.(*CurrentWorkerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchWorkerStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).WatchState(m, &grpc.GenericServerStream[WatchWorkerStateRequest, core.WorkerState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_WatchStateServer = grpc.ServerStreamingServer[core.WorkerState]

func _SandboxService_WatchSandboxEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSandboxEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).WatchSandboxEvents(m, &grpc.GenericServerStream[WatchSandboxEventsRequest, core.SandboxRemoved]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_WatchSandboxEventsServer = grpc.ServerStreamingServer[core.SandboxRemoved]

func _SandboxService_SetLoadOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoadOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SetLoadOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SetLoadOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SetLoadOverride(ctx, req.(*SetLoadOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperfaas.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareImage",
			Handler:    _SandboxService_PrepareImage_Handler,
		},
		{
			MethodName: "CreateSandbox",
			Handler:    _SandboxService_CreateSandbox_Handler,
		},
		{
			MethodName: "StopSandbox",
			Handler:    _SandboxService_StopSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _SandboxService_ListSandboxes_Handler,
		},
		{
			MethodName: "SignalReady",
			Handler:    _SandboxService_SignalReady_Handler,
		},
		{
			MethodName: "CurrentState",
			Handler:    _SandboxService_CurrentState_Handler,
		},
		{
			MethodName: "SetLoadOverride",
			Handler:    _SandboxService_SetLoadOverride_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchState",
			Handler:       _SandboxService_WatchState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSandboxEvents",
			Handler:       _SandboxService_WatchSandboxEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}
