// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	core "hyperfaas-ideal-arch/pkg/core"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *core.FunctionSpec     `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareImageRequest) Reset() {
	*x = PrepareImageRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareImageRequest) ProtoMessage() {}

func (x *PrepareImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareImageRequest.ProtoReflect.Descriptor instead.
func (*PrepareImageRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareImageRequest) GetFunction() *core.FunctionSpec {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Request       *core.StartSandboxRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxRequest) GetRequest() *core.StartSandboxRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type StopSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *StopSandboxRequest) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type StopSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxResponse) Reset() {
	*x = StopSandboxResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxResponse) ProtoMessage() {}

func (x *StopSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxResponse.ProtoReflect.Descriptor instead.
func (*StopSandboxResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*core.InstanceState  `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ListSandboxesResponse) GetInstances() []*core.InstanceState {
	if x != nil {
		return x.Instances
	}
	return nil
}

type SignalReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalReadyRequest) Reset() {
	*x = SignalReadyRequest{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalReadyRequest) ProtoMessage() {}

func (x *SignalReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalReadyRequest.ProtoReflect.Descriptor instead.
func (*SignalReadyRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *SignalReadyRequest) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type SignalReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalReadyResponse) Reset() {
	*x = SignalReadyResponse{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalReadyResponse) ProtoMessage() {}

func (x *SignalReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalReadyResponse.ProtoReflect.Descriptor instead.
func (*SignalReadyResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

// Diagnostic-only request for a full worker snapshot.
type CurrentWorkerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentWorkerStateRequest) Reset() {
	*x = CurrentWorkerStateRequest{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentWorkerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentWorkerStateRequest) ProtoMessage() {}

func (x *CurrentWorkerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentWorkerStateRequest.ProtoReflect.Descriptor instead.
func (*CurrentWorkerStateRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

// WorkerStateProjection selects which optional worker-state fields the leaf
// asks the worker to compute and send. Lifecycle-authoritative state (sandbox
// states, instance count, capacity, allocated resources) is always sent and is
// not part of this projection. See docs/DYNAMIC_POLICY_STATE_GATING_DESIGN.md.
type WorkerStateProjection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// load_average_norm: the normalized 1-minute load average. Used by
	// resource-aware and bounded-loads placement, and by the leaf's leaf_load
	// routing signal.
	LoadAverageNorm bool `protobuf:"varint,1,opt,name=load_average_norm,json=loadAverageNorm,proto3" json:"load_average_norm,omitempty"`
	// cached_images: the local image cache. Used by image-aware placement.
	CachedImages  bool `protobuf:"varint,2,opt,name=cached_images,json=cachedImages,proto3" json:"cached_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStateProjection) Reset() {
	*x = WorkerStateProjection{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStateProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStateProjection) ProtoMessage() {}

func (x *WorkerStateProjection) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStateProjection.ProtoReflect.Descriptor instead.
func (*WorkerStateProjection) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *WorkerStateProjection) GetLoadAverageNorm() bool {
	if x != nil {
		return x.LoadAverageNorm
	}
	return false
}

func (x *WorkerStateProjection) GetCachedImages() bool {
	if x != nil {
		return x.CachedImages
	}
	return false
}

type WatchWorkerStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config_version is the PlatformConfig version whose projection this stream
	// was opened for. The worker does not subscribe to PlatformConfig, so it
	// treats this as advisory and gates purely on projection. See server.go.
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Projection    *WorkerStateProjection `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchWorkerStateRequest) Reset() {
	*x = WatchWorkerStateRequest{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkerStateRequest) ProtoMessage() {}

func (x *WatchWorkerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkerStateRequest.ProtoReflect.Descriptor instead.
func (*WatchWorkerStateRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *WatchWorkerStateRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *WatchWorkerStateRequest) GetProjection() *WorkerStateProjection {
	if x != nil {
		return x.Projection
	}
	return nil
}

type WatchSandboxEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSandboxEventsRequest) Reset() {
	*x = WatchSandboxEventsRequest{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSandboxEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSandboxEventsRequest) ProtoMessage() {}

func (x *WatchSandboxEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSandboxEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchSandboxEventsRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

type SetLoadOverrideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LoadAverageNorm float64                `protobuf:"fixed64,1,opt,name=load_average_norm,json=loadAverageNorm,proto3" json:"load_average_norm,omitempty"`
	Clear           bool                   `protobuf:"varint,2,opt,name=clear,proto3" json:"clear,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetLoadOverrideRequest) Reset() {
	*x = SetLoadOverrideRequest{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoadOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoadOverrideRequest) ProtoMessage() {}

func (x *SetLoadOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoadOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetLoadOverrideRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *SetLoadOverrideRequest) GetLoadAverageNorm() float64 {
	if x != nil {
		return x.LoadAverageNorm
	}
	return 0
}

func (x *SetLoadOverrideRequest) GetClear() bool {
	if x != nil {
		return x.Clear
	}
	return false
}

type SetLoadOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoadOverrideResponse) Reset() {
	*x = SetLoadOverrideResponse{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoadOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoadOverrideResponse) ProtoMessage() {}

func (x *SetLoadOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoadOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetLoadOverrideResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\thyperfaas\x1a\n" +
	"core.proto\"J\n" +
	"\x13PrepareImageRequest\x123\n" +
	"\bfunction\x18\x01 \x01(\v2\x17.hyperfaas.FunctionSpecR\bfunction\"P\n" +
	"\x14CreateSandboxRequest\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.hyperfaas.StartSandboxRequestR\arequest\"5\n" +
	"\x12StopSandboxRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\"\x15\n" +
	"\x13StopSandboxResponse\"\x16\n" +
	"\x14ListSandboxesRequest\"O\n" +
	"\x15ListSandboxesResponse\x126\n" +
	"\tinstances\x18\x01 \x03(\v2\x18.hyperfaas.InstanceStateR\tinstances\"5\n" +
	"\x12SignalReadyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\"\x15\n" +
	"\x13SignalReadyResponse\"\x1b\n" +
	"\x19CurrentWorkerStateRequest\"h\n" +
	"\x15WorkerStateProjection\x12*\n" +
	"\x11load_average_norm\x18\x01 \x01(\bR\x0floadAverageNorm\x12#\n" +
	"\rcached_images\x18\x02 \x01(\bR\fcachedImages\"\x82\x01\n" +
	"\x17WatchWorkerStateRequest\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12@\n" +
	"\n" +
	"projection\x18\x02 \x01(\v2 .hyperfaas.WorkerStateProjectionR\n" +
	"projection\"\x1b\n" +
	"\x19WatchSandboxEventsRequest\"Z\n" +
	"\x16SetLoadOverrideRequest\x12*\n" +
	"\x11load_average_norm\x18\x01 \x01(\x01R\x0floadAverageNorm\x12\x14\n" +
	"\x05clear\x18\x02 \x01(\bR\x05clear\"\x19\n" +
	"\x17SetLoadOverrideResponse2\xe6\x05\n" +
	"\x0eSandboxService\x12K\n" +
	"\fPrepareImage\x12\x1e.hyperfaas.PrepareImageRequest\x1a\x1b.hyperfaas.PreparedArtifact\x12J\n" +
	"\rCreateSandbox\x12\x1f.hyperfaas.CreateSandboxRequest\x1a\x18.hyperfaas.InstanceState\x12L\n" +
	"\vStopSandbox\x12\x1d.hyperfaas.StopSandboxRequest\x1a\x1e.hyperfaas.StopSandboxResponse\x12R\n" +
	"\rListSandboxes\x12\x1f.hyperfaas.ListSandboxesRequest\x1a .hyperfaas.ListSandboxesResponse\x12L\n" +
	"\vSignalReady\x12\x1d.hyperfaas.SignalReadyRequest\x1a\x1e.hyperfaas.SignalReadyResponse\x12L\n" +
	"\fCurrentState\x12$.hyperfaas.CurrentWorkerStateRequest\x1a\x16.hyperfaas.WorkerState\x12J\n" +
	"\n" +
	"WatchState\x12\".hyperfaas.WatchWorkerStateRequest\x1a\x16.hyperfaas.WorkerState0\x01\x12W\n" +
	"\x12WatchSandboxEvents\x12$.hyperfaas.WatchSandboxEventsRequest\x1a\x19.hyperfaas.SandboxRemoved0\x01\x12X\n" +
	"\x0fSetLoadOverride\x12!.hyperfaas.SetLoadOverrideRequest\x1a\".hyperfaas.SetLoadOverrideResponseB#Z!hyperfaas-ideal-arch/pkg/workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_worker_proto_goTypes = []any{
	(*PrepareImageRequest)(nil),       // 0: hyperfaas.PrepareImageRequest
	(*CreateSandboxRequest)(nil),      // 1: hyperfaas.CreateSandboxRequest
	(*StopSandboxRequest)(nil),        // 2: hyperfaas.StopSandboxRequest
	(*StopSandboxResponse)(nil),       // 3: hyperfaas.StopSandboxResponse
	(*ListSandboxesRequest)(nil),      // 4: hyperfaas.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),     // 5: hyperfaas.ListSandboxesResponse
	(*SignalReadyRequest)(nil),        // 6: hyperfaas.SignalReadyRequest
	(*SignalReadyResponse)(nil),       // 7: hyperfaas.SignalReadyResponse
	(*CurrentWorkerStateRequest)(nil), // 8: hyperfaas.CurrentWorkerStateRequest
	(*WorkerStateProjection)(nil),     // 9: hyperfaas.WorkerStateProjection
	(*WatchWorkerStateRequest)(nil),   // 10: hyperfaas.WatchWorkerStateRequest
	(*WatchSandboxEventsRequest)(nil), // 11: hyperfaas.WatchSandboxEventsRequest
	(*SetLoadOverrideRequest)(nil),    // 12: hyperfaas.SetLoadOverrideRequest
	(*SetLoadOverrideResponse)(nil),   // 13: hyperfaas.SetLoadOverrideResponse
	(*core.FunctionSpec)(nil),         // 14: hyperfaas.FunctionSpec
	(*core.StartSandboxRequest)(nil),  // 15: hyperfaas.StartSandboxRequest
	(*core.InstanceState)(nil),        // 16: hyperfaas.InstanceState
	(*core.PreparedArtifact)(nil),     // 17: hyperfaas.PreparedArtifact
	(*core.WorkerState)(nil),          // 18: hyperfaas.WorkerState
	(*core.SandboxRemoved)(nil),       // 19: hyperfaas.SandboxRemoved
}
var file_worker_proto_depIdxs = []int32{
	14, // 0: hyperfaas.PrepareImageRequest.function:type_name -> hyperfaas.FunctionSpec
	15, // 1: hyperfaas.CreateSandboxRequest.request:type_name -> hyperfaas.StartSandboxRequest
	16, // 2: hyperfaas.ListSandboxesResponse.instances:type_name -> hyperfaas.InstanceState
	9,  // 3: hyperfaas.WatchWorkerStateRequest.projection:type_name -> hyperfaas.WorkerStateProjection
	0,  // 4: hyperfaas.SandboxService.PrepareImage:input_type -> hyperfaas.PrepareImageRequest
	1,  // 5: hyperfaas.SandboxService.CreateSandbox:input_type -> hyperfaas.CreateSandboxRequest
	2,  // 6: hyperfaas.SandboxService.StopSandbox:input_type -> hyperfaas.StopSandboxRequest
	4,  // 7: hyperfaas.SandboxService.ListSandboxes:input_type -> hyperfaas.ListSandboxesRequest
	6,  // 8: hyperfaas.SandboxService.SignalReady:input_type -> hyperfaas.SignalReadyRequest
	8,  // 9: hyperfaas.SandboxService.CurrentState:input_type -> hyperfaas.CurrentWorkerStateRequest
	10, // 10: hyperfaas.SandboxService.WatchState:input_type -> hyperfaas.WatchWorkerStateRequest
	11, // 11: hyperfaas.SandboxService.WatchSandboxEvents:input_type -> hyperfaas.WatchSandboxEventsRequest
	12, // 12: hyperfaas.SandboxService.SetLoadOverride:input_type -> hyperfaas.SetLoadOverrideRequest
	17, // 13: hyperfaas.SandboxService.PrepareImage:output_type -> hyperfaas.PreparedArtifact
	16, // 14: hyperfaas.SandboxService.CreateSandbox:output_type -> hyperfaas.InstanceState
	3,  // 15: hyperfaas.SandboxService.StopSandbox:output_type -> hyperfaas.StopSandboxResponse
	5,  // 16: hyperfaas.SandboxService.ListSandboxes:output_type -> hyperfaas.ListSandboxesResponse
	7,  // 17: hyperfaas.SandboxService.SignalReady:output_type -> hyperfaas.SignalReadyResponse
	18, // 18: hyperfaas.SandboxService.CurrentState:output_type -> hyperfaas.WorkerState
	18, // 19: hyperfaas.SandboxService.WatchState:output_type -> hyperfaas.WorkerState
	19, // 20: hyperfaas.SandboxService.WatchSandboxEvents:output_type -> hyperfaas.SandboxRemoved
	13, // 21: hyperfaas.SandboxService.SetLoadOverride:output_type -> hyperfaas.SetLoadOverrideResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
