// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: controlplane.proto

package controlplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	core "hyperfaas-ideal-arch/pkg/core"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *core.FunctionSpec     `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	mi := &file_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFunctionRequest) GetFunction() *core.FunctionSpec {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFunctionResponse) Reset() {
	*x = CreateFunctionResponse{}
	mi := &file_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionResponse) ProtoMessage() {}

func (x *CreateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionResponse.ProtoReflect.Descriptor instead.
func (*CreateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{1}
}

type UpdateFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *core.FunctionSpec     `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFunctionRequest) Reset() {
	*x = UpdateFunctionRequest{}
	mi := &file_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionRequest) ProtoMessage() {}

func (x *UpdateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFunctionRequest) GetFunction() *core.FunctionSpec {
	if x != nil {
		return x.Function
	}
	return nil
}

type UpdateFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFunctionResponse) Reset() {
	*x = UpdateFunctionResponse{}
	mi := &file_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionResponse) ProtoMessage() {}

func (x *UpdateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionResponse.ProtoReflect.Descriptor instead.
func (*UpdateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{3}
}

type DeleteFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FunctionId    uint64                 `protobuf:"varint,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFunctionRequest) Reset() {
	*x = DeleteFunctionRequest{}
	mi := &file_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionRequest) ProtoMessage() {}

func (x *DeleteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionRequest.ProtoReflect.Descriptor instead.
func (*DeleteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFunctionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFunctionRequest) GetFunctionId() uint64 {
	if x != nil {
		return x.FunctionId
	}
	return 0
}

type DeleteFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFunctionResponse) Reset() {
	*x = DeleteFunctionResponse{}
	mi := &file_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionResponse) ProtoMessage() {}

func (x *DeleteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionResponse.ProtoReflect.Descriptor instead.
func (*DeleteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{5}
}

type GetFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FunctionId    uint64                 `protobuf:"varint,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionRequest) Reset() {
	*x = GetFunctionRequest{}
	mi := &file_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionRequest) ProtoMessage() {}

func (x *GetFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *GetFunctionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFunctionRequest) GetFunctionId() uint64 {
	if x != nil {
		return x.FunctionId
	}
	return 0
}

type GetFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *core.FunctionSpec     `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionResponse) Reset() {
	*x = GetFunctionResponse{}
	mi := &file_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionResponse) ProtoMessage() {}

func (x *GetFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *GetFunctionResponse) GetFunction() *core.FunctionSpec {
	if x != nil {
		return x.Function
	}
	return nil
}

type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *ListFunctionsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*core.FunctionSpec   `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *ListFunctionsResponse) GetFunctions() []*core.FunctionSpec {
	if x != nil {
		return x.Functions
	}
	return nil
}

type WatchFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchFunctionsRequest) Reset() {
	*x = WatchFunctionsRequest{}
	mi := &file_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFunctionsRequest) ProtoMessage() {}

func (x *WatchFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFunctionsRequest.ProtoReflect.Descriptor instead.
func (*WatchFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{10}
}

type GetPlatformConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformConfigRequest) Reset() {
	*x = GetPlatformConfigRequest{}
	mi := &file_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformConfigRequest) ProtoMessage() {}

func (x *GetPlatformConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformConfigRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{11}
}

type GetPlatformConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *core.PlatformConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformConfigResponse) Reset() {
	*x = GetPlatformConfigResponse{}
	mi := &file_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformConfigResponse) ProtoMessage() {}

func (x *GetPlatformConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformConfigResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *GetPlatformConfigResponse) GetConfig() *core.PlatformConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type PutPlatformConfigRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config *core.PlatformConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Optimistic concurrency. When non-zero the write is rejected unless the
	// stored document has exactly this version. Zero writes unconditionally.
	ExpectedVersion uint64 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutPlatformConfigRequest) Reset() {
	*x = PutPlatformConfigRequest{}
	mi := &file_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPlatformConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPlatformConfigRequest) ProtoMessage() {}

func (x *PutPlatformConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPlatformConfigRequest.ProtoReflect.Descriptor instead.
func (*PutPlatformConfigRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *PutPlatformConfigRequest) GetConfig() *core.PlatformConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PutPlatformConfigRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type PutPlatformConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *core.PlatformConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPlatformConfigResponse) Reset() {
	*x = PutPlatformConfigResponse{}
	mi := &file_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPlatformConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPlatformConfigResponse) ProtoMessage() {}

func (x *PutPlatformConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPlatformConfigResponse.ProtoReflect.Descriptor instead.
func (*PutPlatformConfigResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *PutPlatformConfigResponse) GetConfig() *core.PlatformConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type WatchPlatformConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPlatformConfigRequest) Reset() {
	*x = WatchPlatformConfigRequest{}
	mi := &file_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPlatformConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPlatformConfigRequest) ProtoMessage() {}

func (x *WatchPlatformConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPlatformConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchPlatformConfigRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{15}
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *core.UserSpec         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *CreateUserRequest) GetUser() *core.UserSpec {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{17}
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *core.UserSpec         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_controlplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateUserRequest) GetUser() *core.UserSpec {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_controlplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{19}
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_controlplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_controlplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{21}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_controlplane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *core.UserSpec         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_controlplane_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserResponse) GetUser() *core.UserSpec {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_controlplane_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{24}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*core.UserSpec       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_controlplane_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{25}
}

func (x *ListUsersResponse) GetUsers() []*core.UserSpec {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x12controlplane.proto\x12\thyperfaas\x1a\n" +
	"core.proto\"L\n" +
	"\x15CreateFunctionRequest\x123\n" +
	"\bfunction\x18\x01 \x01(\v2\x17.hyperfaas.FunctionSpecR\bfunction\"\x18\n" +
	"\x16CreateFunctionResponse\"L\n" +
	"\x15UpdateFunctionRequest\x123\n" +
	"\bfunction\x18\x01 \x01(\v2\x17.hyperfaas.FunctionSpecR\bfunction\"\x18\n" +
	"\x16UpdateFunctionResponse\"Q\n" +
	"\x15DeleteFunctionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\x04R\n" +
	"functionId\"\x18\n" +
	"\x16DeleteFunctionResponse\"N\n" +
	"\x12GetFunctionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\x04R\n" +
	"functionId\"J\n" +
	"\x13GetFunctionResponse\x123\n" +
	"\bfunction\x18\x01 \x01(\v2\x17.hyperfaas.FunctionSpecR\bfunction\"/\n" +
	"\x14ListFunctionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"N\n" +
	"\x15ListFunctionsResponse\x125\n" +
	"\tfunctions\x18\x01 \x03(\v2\x17.hyperfaas.FunctionSpecR\tfunctions\"\x17\n" +
	"\x15WatchFunctionsRequest\"\x1a\n" +
	"\x18GetPlatformConfigRequest\"N\n" +
	"\x19GetPlatformConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.hyperfaas.PlatformConfigR\x06config\"x\n" +
	"\x18PutPlatformConfigRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.hyperfaas.PlatformConfigR\x06config\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\"N\n" +
	"\x19PutPlatformConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.hyperfaas.PlatformConfigR\x06config\"\x1c\n" +
	"\x1aWatchPlatformConfigRequest\"<\n" +
	"\x11CreateUserRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.hyperfaas.UserSpecR\x04user\"\x14\n" +
	"\x12CreateUserResponse\"<\n" +
	"\x11UpdateUserRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.hyperfaas.UserSpecR\x04user\"\x14\n" +
	"\x12UpdateUserResponse\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\":\n" +
	"\x0fGetUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.hyperfaas.UserSpecR\x04user\"\x12\n" +
	"\x10ListUsersRequest\">\n" +
	"\x11ListUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.hyperfaas.UserSpecR\x05users2\x88\x04\n" +
	"\x0fFunctionService\x12U\n" +
	"\x0eCreateFunction\x12 .hyperfaas.CreateFunctionRequest\x1a!.hyperfaas.CreateFunctionResponse\x12U\n" +
	"\x0eUpdateFunction\x12 .hyperfaas.UpdateFunctionRequest\x1a!.hyperfaas.UpdateFunctionResponse\x12U\n" +
	"\x0eDeleteFunction\x12 .hyperfaas.DeleteFunctionRequest\x1a!.hyperfaas.DeleteFunctionResponse\x12L\n" +
	"\vGetFunction\x12\x1d.hyperfaas.GetFunctionRequest\x1a\x1e.hyperfaas.GetFunctionResponse\x12R\n" +
	"\rListFunctions\x12\x1f.hyperfaas.ListFunctionsRequest\x1a .hyperfaas.ListFunctionsResponse\x12N\n" +
	"\x0eWatchFunctions\x12 .hyperfaas.WatchFunctionsRequest\x1a\x18.hyperfaas.FunctionEvent0\x012\xf8\x02\n" +
	"\vUserService\x12I\n" +
	"\n" +
	"CreateUser\x12\x1c.hyperfaas.CreateUserRequest\x1a\x1d.hyperfaas.CreateUserResponse\x12I\n" +
	"\n" +
	"UpdateUser\x12\x1c.hyperfaas.UpdateUserRequest\x1a\x1d.hyperfaas.UpdateUserResponse\x12I\n" +
	"\n" +
	"DeleteUser\x12\x1c.hyperfaas.DeleteUserRequest\x1a\x1d.hyperfaas.DeleteUserResponse\x12@\n" +
	"\aGetUser\x12\x19.hyperfaas.GetUserRequest\x1a\x1a.hyperfaas.GetUserResponse\x12F\n" +
	"\tListUsers\x12\x1b.hyperfaas.ListUsersRequest\x1a\x1c.hyperfaas.ListUsersResponse2\xaa\x02\n" +
	"\rConfigService\x12^\n" +
	"\x11GetPlatformConfig\x12#.hyperfaas.GetPlatformConfigRequest\x1a$.hyperfaas.GetPlatformConfigResponse\x12^\n" +
	"\x11PutPlatformConfig\x12#.hyperfaas.PutPlatformConfigRequest\x1a$.hyperfaas.PutPlatformConfigResponse\x12Y\n" +
	"\x13WatchPlatformConfig\x12%.hyperfaas.WatchPlatformConfigRequest\x1a\x19.hyperfaas.PlatformConfig0\x01B'Z%hyperfaas-ideal-arch/pkg/controlplaneb\x06proto3"

var (
	file_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_proto_rawDescData []byte
)

func file_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)))
	})
	return file_controlplane_proto_rawDescData
}

var file_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_controlplane_proto_goTypes = []any{
	(*CreateFunctionRequest)(nil),      // 0: hyperfaas.CreateFunctionRequest
	(*CreateFunctionResponse)(nil),     // 1: hyperfaas.CreateFunctionResponse
	(*UpdateFunctionRequest)(nil),      // 2: hyperfaas.UpdateFunctionRequest
	(*UpdateFunctionResponse)(nil),     // 3: hyperfaas.UpdateFunctionResponse
	(*DeleteFunctionRequest)(nil),      // 4: hyperfaas.DeleteFunctionRequest
	(*DeleteFunctionResponse)(nil),     // 5: hyperfaas.DeleteFunctionResponse
	(*GetFunctionRequest)(nil),         // 6: hyperfaas.GetFunctionRequest
	(*GetFunctionResponse)(nil),        // 7: hyperfaas.GetFunctionResponse
	(*ListFunctionsRequest)(nil),       // 8: hyperfaas.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),      // 9: hyperfaas.ListFunctionsResponse
	(*WatchFunctionsRequest)(nil),      // 10: hyperfaas.WatchFunctionsRequest
	(*GetPlatformConfigRequest)(nil),   // 11: hyperfaas.GetPlatformConfigRequest
	(*GetPlatformConfigResponse)(nil),  // 12: hyperfaas.GetPlatformConfigResponse
	(*PutPlatformConfigRequest)(nil),   // 13: hyperfaas.PutPlatformConfigRequest
	(*PutPlatformConfigResponse)(nil),  // 14: hyperfaas.PutPlatformConfigResponse
	(*WatchPlatformConfigRequest)(nil), // 15: hyperfaas.WatchPlatformConfigRequest
	(*CreateUserRequest)(nil),          // 16: hyperfaas.CreateUserRequest
	(*CreateUserResponse)(nil),         // 17: hyperfaas.CreateUserResponse
	(*UpdateUserRequest)(nil),          // 18: hyperfaas.UpdateUserRequest
	(*UpdateUserResponse)(nil),         // 19: hyperfaas.UpdateUserResponse
	(*DeleteUserRequest)(nil),          // 20: hyperfaas.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 21: hyperfaas.DeleteUserResponse
	(*GetUserRequest)(nil),             // 22: hyperfaas.GetUserRequest
	(*GetUserResponse)(nil),            // 23: hyperfaas.GetUserResponse
	(*ListUsersRequest)(nil),           // 24: hyperfaas.ListUsersRequest
	(*ListUsersResponse)(nil),          // 25: hyperfaas.ListUsersResponse
	(*core.FunctionSpec)(nil),          // 26: hyperfaas.FunctionSpec
	(*core.PlatformConfig)(nil),        // 27: hyperfaas.PlatformConfig
	(*core.UserSpec)(nil),              // 28: hyperfaas.UserSpec
	(*core.FunctionEvent)(nil),         // 29: hyperfaas.FunctionEvent
}
var file_controlplane_proto_depIdxs = []int32{
	26, // 0: hyperfaas.CreateFunctionRequest.function:type_name -> hyperfaas.FunctionSpec
	26, // 1: hyperfaas.UpdateFunctionRequest.function:type_name -> hyperfaas.FunctionSpec
	26, // 2: hyperfaas.GetFunctionResponse.function:type_name -> hyperfaas.FunctionSpec
	26, // 3: hyperfaas.ListFunctionsResponse.functions:type_name -> hyperfaas.FunctionSpec
	27, // 4: hyperfaas.GetPlatformConfigResponse.config:type_name -> hyperfaas.PlatformConfig
	27, // 5: hyperfaas.PutPlatformConfigRequest.config:type_name -> hyperfaas.PlatformConfig
	27, // 6: hyperfaas.PutPlatformConfigResponse.config:type_name -> hyperfaas.PlatformConfig
	28, // 7: hyperfaas.CreateUserRequest.user:type_name -> hyperfaas.UserSpec
	28, // 8: hyperfaas.UpdateUserRequest.user:type_name -> hyperfaas.UserSpec
	28, // 9: hyperfaas.GetUserResponse.user:type_name -> hyperfaas.UserSpec
	28, // 10: hyperfaas.ListUsersResponse.users:type_name -> hyperfaas.UserSpec
	0,  // 11: hyperfaas.FunctionService.CreateFunction:input_type -> hyperfaas.CreateFunctionRequest
	2,  // 12: hyperfaas.FunctionService.UpdateFunction:input_type -> hyperfaas.UpdateFunctionRequest
	4,  // 13: hyperfaas.FunctionService.DeleteFunction:input_type -> hyperfaas.DeleteFunctionRequest
	6,  // 14: hyperfaas.FunctionService.GetFunction:input_type -> hyperfaas.GetFunctionRequest
	8,  // 15: hyperfaas.FunctionService.ListFunctions:input_type -> hyperfaas.ListFunctionsRequest
	10, // 16: hyperfaas.FunctionService.WatchFunctions:input_type -> hyperfaas.WatchFunctionsRequest
	16, // 17: hyperfaas.UserService.CreateUser:input_type -> hyperfaas.CreateUserRequest
	18, // 18: hyperfaas.UserService.UpdateUser:input_type -> hyperfaas.UpdateUserRequest
	20, // 19: hyperfaas.UserService.DeleteUser:input_type -> hyperfaas.DeleteUserRequest
	22, // 20: hyperfaas.UserService.GetUser:input_type -> hyperfaas.GetUserRequest
	24, // 21: hyperfaas.UserService.ListUsers:input_type -> hyperfaas.ListUsersRequest
	11, // 22: hyperfaas.ConfigService.GetPlatformConfig:input_type -> hyperfaas.GetPlatformConfigRequest
	13, // 23: hyperfaas.ConfigService.PutPlatformConfig:input_type -> hyperfaas.PutPlatformConfigRequest
	15, // 24: hyperfaas.ConfigService.WatchPlatformConfig:input_type -> hyperfaas.WatchPlatformConfigRequest
	1,  // 25: hyperfaas.FunctionService.CreateFunction:output_type -> hyperfaas.CreateFunctionResponse
	3,  // 26: hyperfaas.FunctionService.UpdateFunction:output_type -> hyperfaas.UpdateFunctionResponse
	5,  // 27: hyperfaas.FunctionService.DeleteFunction:output_type -> hyperfaas.DeleteFunctionResponse
	7,  // 28: hyperfaas.FunctionService.GetFunction:output_type -> hyperfaas.GetFunctionResponse
	9,  // 29: hyperfaas.FunctionService.ListFunctions:output_type -> hyperfaas.ListFunctionsResponse
	29, // 30: hyperfaas.FunctionService.WatchFunctions:output_type -> hyperfaas.FunctionEvent
	17, // 31: hyperfaas.UserService.CreateUser:output_type -> hyperfaas.CreateUserResponse
	19, // 32: hyperfaas.UserService.UpdateUser:output_type -> hyperfaas.UpdateUserResponse
	21, // 33: hyperfaas.UserService.DeleteUser:output_type -> hyperfaas.DeleteUserResponse
	23, // 34: hyperfaas.UserService.GetUser:output_type -> hyperfaas.GetUserResponse
	25, // 35: hyperfaas.UserService.ListUsers:output_type -> hyperfaas.ListUsersResponse
	12, // 36: hyperfaas.ConfigService.GetPlatformConfig:output_type -> hyperfaas.GetPlatformConfigResponse
	14, // 37: hyperfaas.ConfigService.PutPlatformConfig:output_type -> hyperfaas.PutPlatformConfigResponse
	27, // 38: hyperfaas.ConfigService.WatchPlatformConfig:output_type -> hyperfaas.PlatformConfig
	25, // [25:39] is the sub-list for method output_type
	11, // [11:25] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_controlplane_proto_init() }
func file_controlplane_proto_init() {
	if File_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_depIdxs,
		MessageInfos:      file_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_proto = out.File
	file_controlplane_proto_goTypes = nil
	file_controlplane_proto_depIdxs = nil
}
