[project]
name = "hyperfakeworker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "grpcio-tools>=1.71.0",
    "httpx>=0.28.1",
    "pytest>=8.3.5",
]
