// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: leaf/leaf.proto

package leaf

import (
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *common.Image          `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Config        *common.Config         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	mi := &file_leaf_leaf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFunctionRequest) GetImage() *common.Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CreateFunctionRequest) GetConfig() *common.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFunctionResponse) Reset() {
	*x = CreateFunctionResponse{}
	mi := &file_leaf_leaf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionResponse) ProtoMessage() {}

func (x *CreateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionResponse.ProtoReflect.Descriptor instead.
func (*CreateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFunctionResponse) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

var File_leaf_leaf_proto protoreflect.FileDescriptor

const file_leaf_leaf_proto_rawDesc = "" +
	"\n" +
	"\x0fleaf/leaf.proto\x12\x04leaf\x1a\x13common/common.proto\"d\n" +
	"\x15CreateFunctionRequest\x12#\n" +
	"\x05image\x18\x01 \x01(\v2\r.common.ImageR\x05image\x12&\n" +
	"\x06config\x18\x02 \x01(\v2\x0e.common.ConfigR\x06config\"9\n" +
	"\x16CreateFunctionResponse\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId2\x8e\x01\n" +
	"\x04Leaf\x129\n" +
	"\fScheduleCall\x12\x13.common.CallRequest\x1a\x14.common.CallResponse\x12K\n" +
	"\x0eCreateFunction\x12\x1b.leaf.CreateFunctionRequest\x1a\x1c.leaf.CreateFunctionResponseB-Z+github.com/3s-rg-codes/HyperFaaS/proto/leafb\x06proto3"

var (
	file_leaf_leaf_proto_rawDescOnce sync.Once
	file_leaf_leaf_proto_rawDescData []byte
)

func file_leaf_leaf_proto_rawDescGZIP() []byte {
	file_leaf_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaf_leaf_proto_rawDesc), len(file_leaf_leaf_proto_rawDesc)))
	})
	return file_leaf_leaf_proto_rawDescData
}

var file_leaf_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_leaf_leaf_proto_goTypes = []any{
	(*CreateFunctionRequest)(nil),  // 0: leaf.CreateFunctionRequest
	(*CreateFunctionResponse)(nil), // 1: leaf.CreateFunctionResponse
	(*common.Image)(nil),           // 2: common.Image
	(*common.Config)(nil),          // 3: common.Config
	(*common.CallRequest)(nil),     // 4: common.CallRequest
	(*common.CallResponse)(nil),    // 5: common.CallResponse
}
var file_leaf_leaf_proto_depIdxs = []int32{
	2, // 0: leaf.CreateFunctionRequest.image:type_name -> common.Image
	3, // 1: leaf.CreateFunctionRequest.config:type_name -> common.Config
	4, // 2: leaf.Leaf.ScheduleCall:input_type -> common.CallRequest
	0, // 3: leaf.Leaf.CreateFunction:input_type -> leaf.CreateFunctionRequest
	5, // 4: leaf.Leaf.ScheduleCall:output_type -> common.CallResponse
	1, // 5: leaf.Leaf.CreateFunction:output_type -> leaf.CreateFunctionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_leaf_leaf_proto_init() }
func file_leaf_leaf_proto_init() {
	if File_leaf_leaf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaf_leaf_proto_rawDesc), len(file_leaf_leaf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_leaf_proto_depIdxs,
		MessageInfos:      file_leaf_leaf_proto_msgTypes,
	}.Build()
	File_leaf_leaf_proto = out.File
	file_leaf_leaf_proto_goTypes = nil
	file_leaf_leaf_proto_depIdxs = nil
}
