// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: leaf/leaf.proto

package leaf

import (
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_leaf_leaf_proto protoreflect.FileDescriptor

const file_leaf_leaf_proto_rawDesc = "" +
	"\n" +
	"\x0fleaf/leaf.proto\x12\x04leaf\x1a\x13common/common.proto2>\n" +
	"\x04Leaf\x126\n" +
	"\x05State\x12\x14.common.StateRequest\x1a\x15.common.StateResponse0\x01B-Z+github.com/3s-rg-codes/HyperFaaS/proto/leafb\x06proto3"

var file_leaf_leaf_proto_goTypes = []any{
	(*common.StateRequest)(nil),  // 0: common.StateRequest
	(*common.StateResponse)(nil), // 1: common.StateResponse
}
var file_leaf_leaf_proto_depIdxs = []int32{
	0, // 0: leaf.Leaf.State:input_type -> common.StateRequest
	1, // 1: leaf.Leaf.State:output_type -> common.StateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leaf_leaf_proto_init() }
func file_leaf_leaf_proto_init() {
	if File_leaf_leaf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaf_leaf_proto_rawDesc), len(file_leaf_leaf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_leaf_proto_depIdxs,
	}.Build()
	File_leaf_leaf_proto = out.File
	file_leaf_leaf_proto_goTypes = nil
	file_leaf_leaf_proto_depIdxs = nil
}
