// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: leaf/leaf.proto

package leaf

import (
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduleCallRequest represents a request to the Leaf Node Server to schedule a call to a worker with a given function ID.
type ScheduleCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique identifier of the function to invoke.
	FunctionID *common.FunctionID `protobuf:"bytes,1,opt,name=functionID,proto3" json:"functionID,omitempty"`
	// The data to pass to the function.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ScheduleCallRequest) Reset() {
	*x = ScheduleCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_leaf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCallRequest) ProtoMessage() {}

func (x *ScheduleCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCallRequest.ProtoReflect.Descriptor instead.
func (*ScheduleCallRequest) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleCallRequest) GetFunctionID() *common.FunctionID {
	if x != nil {
		return x.FunctionID
	}
	return nil
}

func (x *ScheduleCallRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScheduleCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The result data from the scheduled function call.
	Data  []byte        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *common.Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ScheduleCallResponse) Reset() {
	*x = ScheduleCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_leaf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCallResponse) ProtoMessage() {}

func (x *ScheduleCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCallResponse.ProtoReflect.Descriptor instead.
func (*ScheduleCallResponse) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleCallResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScheduleCallResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageTag *common.ImageTag `protobuf:"bytes,1,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Config   *common.Config   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_leaf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFunctionRequest) GetImageTag() *common.ImageTag {
	if x != nil {
		return x.ImageTag
	}
	return nil
}

func (x *CreateFunctionRequest) GetConfig() *common.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionID *common.FunctionID `protobuf:"bytes,1,opt,name=functionID,proto3" json:"functionID,omitempty"`
}

func (x *CreateFunctionResponse) Reset() {
	*x = CreateFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_leaf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionResponse) ProtoMessage() {}

func (x *CreateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionResponse.ProtoReflect.Descriptor instead.
func (*CreateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFunctionResponse) GetFunctionID() *common.FunctionID {
	if x != nil {
		return x.FunctionID
	}
	return nil
}

var File_leaf_leaf_proto protoreflect.FileDescriptor

var file_leaf_leaf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x65, 0x61, 0x66, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x13,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x0a, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x14, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6e, 0x0a, 0x15,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x54, 0x61, 0x67, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x4c, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x0a,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x32, 0x9a, 0x01, 0x0a, 0x04, 0x4c,
	0x65, 0x61, 0x66, 0x12, 0x45, 0x0a, 0x0c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x6c,
	0x65, 0x61, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c, 0x65, 0x61, 0x66,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x33, 0x73, 0x2d, 0x72, 0x67, 0x2d, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x2f, 0x48, 0x79, 0x70, 0x65, 0x72, 0x46, 0x61, 0x61, 0x53, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_leaf_leaf_proto_rawDescOnce sync.Once
	file_leaf_leaf_proto_rawDescData = file_leaf_leaf_proto_rawDesc
)

func file_leaf_leaf_proto_rawDescGZIP() []byte {
	file_leaf_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(file_leaf_leaf_proto_rawDescData)
	})
	return file_leaf_leaf_proto_rawDescData
}

var file_leaf_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_leaf_leaf_proto_goTypes = []interface{}{
	(*ScheduleCallRequest)(nil),    // 0: leaf.ScheduleCallRequest
	(*ScheduleCallResponse)(nil),   // 1: leaf.ScheduleCallResponse
	(*CreateFunctionRequest)(nil),  // 2: leaf.CreateFunctionRequest
	(*CreateFunctionResponse)(nil), // 3: leaf.CreateFunctionResponse
	(*common.FunctionID)(nil),      // 4: common.FunctionID
	(*common.Error)(nil),           // 5: common.Error
	(*common.ImageTag)(nil),        // 6: common.ImageTag
	(*common.Config)(nil),          // 7: common.Config
}
var file_leaf_leaf_proto_depIdxs = []int32{
	4, // 0: leaf.ScheduleCallRequest.functionID:type_name -> common.FunctionID
	5, // 1: leaf.ScheduleCallResponse.error:type_name -> common.Error
	6, // 2: leaf.CreateFunctionRequest.image_tag:type_name -> common.ImageTag
	7, // 3: leaf.CreateFunctionRequest.config:type_name -> common.Config
	4, // 4: leaf.CreateFunctionResponse.functionID:type_name -> common.FunctionID
	0, // 5: leaf.Leaf.ScheduleCall:input_type -> leaf.ScheduleCallRequest
	2, // 6: leaf.Leaf.CreateFunction:input_type -> leaf.CreateFunctionRequest
	1, // 7: leaf.Leaf.ScheduleCall:output_type -> leaf.ScheduleCallResponse
	3, // 8: leaf.Leaf.CreateFunction:output_type -> leaf.CreateFunctionResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_leaf_leaf_proto_init() }
func file_leaf_leaf_proto_init() {
	if File_leaf_leaf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leaf_leaf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_leaf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_leaf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_leaf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leaf_leaf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_leaf_proto_depIdxs,
		MessageInfos:      file_leaf_leaf_proto_msgTypes,
	}.Build()
	File_leaf_leaf_proto = out.File
	file_leaf_leaf_proto_rawDesc = nil
	file_leaf_leaf_proto_goTypes = nil
	file_leaf_leaf_proto_depIdxs = nil
}
