// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: leaf.proto

package leaf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	core "hyperfaas-ideal-arch/pkg/core"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *core.FunctionSpec     `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFunctionRequest) Reset() {
	*x = ApplyFunctionRequest{}
	mi := &file_leaf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFunctionRequest) ProtoMessage() {}

func (x *ApplyFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFunctionRequest.ProtoReflect.Descriptor instead.
func (*ApplyFunctionRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyFunctionRequest) GetFunction() *core.FunctionSpec {
	if x != nil {
		return x.Function
	}
	return nil
}

type ApplyFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFunctionResponse) Reset() {
	*x = ApplyFunctionResponse{}
	mi := &file_leaf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFunctionResponse) ProtoMessage() {}

func (x *ApplyFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFunctionResponse.ProtoReflect.Descriptor instead.
func (*ApplyFunctionResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{1}
}

type DeleteLeafFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    uint64                 `protobuf:"varint,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeafFunctionRequest) Reset() {
	*x = DeleteLeafFunctionRequest{}
	mi := &file_leaf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeafFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeafFunctionRequest) ProtoMessage() {}

func (x *DeleteLeafFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeafFunctionRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeafFunctionRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLeafFunctionRequest) GetFunctionId() uint64 {
	if x != nil {
		return x.FunctionId
	}
	return 0
}

type DeleteLeafFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeafFunctionResponse) Reset() {
	*x = DeleteLeafFunctionResponse{}
	mi := &file_leaf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeafFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeafFunctionResponse) ProtoMessage() {}

func (x *DeleteLeafFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeafFunctionResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeafFunctionResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{3}
}

type EnsureCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Demand        *core.ScaleDemand      `protobuf:"bytes,1,opt,name=demand,proto3" json:"demand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureCapacityRequest) Reset() {
	*x = EnsureCapacityRequest{}
	mi := &file_leaf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureCapacityRequest) ProtoMessage() {}

func (x *EnsureCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureCapacityRequest.ProtoReflect.Descriptor instead.
func (*EnsureCapacityRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{4}
}

func (x *EnsureCapacityRequest) GetDemand() *core.ScaleDemand {
	if x != nil {
		return x.Demand
	}
	return nil
}

type EnsureCapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureCapacityResponse) Reset() {
	*x = EnsureCapacityResponse{}
	mi := &file_leaf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureCapacityResponse) ProtoMessage() {}

func (x *EnsureCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureCapacityResponse.ProtoReflect.Descriptor instead.
func (*EnsureCapacityResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{5}
}

// Diagnostic-only request for a full leaf snapshot.
type CurrentLeafStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentLeafStateRequest) Reset() {
	*x = CurrentLeafStateRequest{}
	mi := &file_leaf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentLeafStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentLeafStateRequest) ProtoMessage() {}

func (x *CurrentLeafStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentLeafStateRequest.ProtoReflect.Descriptor instead.
func (*CurrentLeafStateRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{6}
}

// RoutingStateProjection selects the routing state a subscriber needs. A field
// left false is never computed, serialized, or retained by the producer.
type RoutingStateProjection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeafLoad          bool                   `protobuf:"varint,1,opt,name=leaf_load,json=leafLoad,proto3" json:"leaf_load,omitempty"`
	AggregateInFlight bool                   `protobuf:"varint,2,opt,name=aggregate_in_flight,json=aggregateInFlight,proto3" json:"aggregate_in_flight,omitempty"`
	FunctionCapacity  bool                   `protobuf:"varint,3,opt,name=function_capacity,json=functionCapacity,proto3" json:"function_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoutingStateProjection) Reset() {
	*x = RoutingStateProjection{}
	mi := &file_leaf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingStateProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingStateProjection) ProtoMessage() {}

func (x *RoutingStateProjection) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingStateProjection.ProtoReflect.Descriptor instead.
func (*RoutingStateProjection) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{7}
}

func (x *RoutingStateProjection) GetLeafLoad() bool {
	if x != nil {
		return x.LeafLoad
	}
	return false
}

func (x *RoutingStateProjection) GetAggregateInFlight() bool {
	if x != nil {
		return x.AggregateInFlight
	}
	return false
}

func (x *RoutingStateProjection) GetFunctionCapacity() bool {
	if x != nil {
		return x.FunctionCapacity
	}
	return false
}

type WatchRoutingStateRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ConfigVersion uint64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Projection    *RoutingStateProjection `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoutingStateRequest) Reset() {
	*x = WatchRoutingStateRequest{}
	mi := &file_leaf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingStateRequest) ProtoMessage() {}

func (x *WatchRoutingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingStateRequest.ProtoReflect.Descriptor instead.
func (*WatchRoutingStateRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{8}
}

func (x *WatchRoutingStateRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *WatchRoutingStateRequest) GetProjection() *RoutingStateProjection {
	if x != nil {
		return x.Projection
	}
	return nil
}

// RoutingStateFrame is one leaf's routing state for one configuration version.
//
// Scalar fields are optional and present only when the projection requested
// them. The first frame of a stream has full_snapshot set and carries the
// complete capacity set for the projection; later frames carry only changes.
// Every frame carries the configuration version and a monotonic per-leaf
// revision so a consumer can reject foreign-version, duplicate, and
// out-of-order frames.
type RoutingStateFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	LeafId        uint64                 `protobuf:"varint,2,opt,name=leaf_id,json=leafId,proto3" json:"leaf_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	FullSnapshot  bool                   `protobuf:"varint,4,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	// Number of workers that can currently accept new sandboxes. A connected leaf
	// with zero healthy workers must not receive routing decisions.
	HealthyWorkers    uint32                   `protobuf:"varint,5,opt,name=healthy_workers,json=healthyWorkers,proto3" json:"healthy_workers,omitempty"`
	LeafLoad          *float64                 `protobuf:"fixed64,6,opt,name=leaf_load,json=leafLoad,proto3,oneof" json:"leaf_load,omitempty"`
	AggregateInFlight *uint64                  `protobuf:"varint,7,opt,name=aggregate_in_flight,json=aggregateInFlight,proto3,oneof" json:"aggregate_in_flight,omitempty"`
	Capacities        []*core.FunctionCapacity `protobuf:"bytes,8,rep,name=capacities,proto3" json:"capacities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoutingStateFrame) Reset() {
	*x = RoutingStateFrame{}
	mi := &file_leaf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingStateFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingStateFrame) ProtoMessage() {}

func (x *RoutingStateFrame) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingStateFrame.ProtoReflect.Descriptor instead.
func (*RoutingStateFrame) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{9}
}

func (x *RoutingStateFrame) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *RoutingStateFrame) GetLeafId() uint64 {
	if x != nil {
		return x.LeafId
	}
	return 0
}

func (x *RoutingStateFrame) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RoutingStateFrame) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

func (x *RoutingStateFrame) GetHealthyWorkers() uint32 {
	if x != nil {
		return x.HealthyWorkers
	}
	return 0
}

func (x *RoutingStateFrame) GetLeafLoad() float64 {
	if x != nil && x.LeafLoad != nil {
		return *x.LeafLoad
	}
	return 0
}

func (x *RoutingStateFrame) GetAggregateInFlight() uint64 {
	if x != nil && x.AggregateInFlight != nil {
		return *x.AggregateInFlight
	}
	return 0
}

func (x *RoutingStateFrame) GetCapacities() []*core.FunctionCapacity {
	if x != nil {
		return x.Capacities
	}
	return nil
}

var File_leaf_proto protoreflect.FileDescriptor

const file_leaf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"leaf.proto\x12\thyperfaas\x1a\n" +
	"core.proto\"K\n" +
	"\x14ApplyFunctionRequest\x123\n" +
	"\bfunction\x18\x01 \x01(\v2\x17.hyperfaas.FunctionSpecR\bfunction\"\x17\n" +
	"\x15ApplyFunctionResponse\"<\n" +
	"\x19DeleteLeafFunctionRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\x04R\n" +
	"functionId\"\x1c\n" +
	"\x1aDeleteLeafFunctionResponse\"G\n" +
	"\x15EnsureCapacityRequest\x12.\n" +
	"\x06demand\x18\x01 \x01(\v2\x16.hyperfaas.ScaleDemandR\x06demand\"\x18\n" +
	"\x16EnsureCapacityResponse\"\x19\n" +
	"\x17CurrentLeafStateRequest\"\x92\x01\n" +
	"\x16RoutingStateProjection\x12\x1b\n" +
	"\tleaf_load\x18\x01 \x01(\bR\bleafLoad\x12.\n" +
	"\x13aggregate_in_flight\x18\x02 \x01(\bR\x11aggregateInFlight\x12+\n" +
	"\x11function_capacity\x18\x03 \x01(\bR\x10functionCapacity\"\x84\x01\n" +
	"\x18WatchRoutingStateRequest\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12A\n" +
	"\n" +
	"projection\x18\x02 \x01(\v2!.hyperfaas.RoutingStateProjectionR\n" +
	"projection\"\xf7\x02\n" +
	"\x11RoutingStateFrame\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12\x17\n" +
	"\aleaf_id\x18\x02 \x01(\x04R\x06leafId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12#\n" +
	"\rfull_snapshot\x18\x04 \x01(\bR\ffullSnapshot\x12'\n" +
	"\x0fhealthy_workers\x18\x05 \x01(\rR\x0ehealthyWorkers\x12 \n" +
	"\tleaf_load\x18\x06 \x01(\x01H\x00R\bleafLoad\x88\x01\x01\x123\n" +
	"\x13aggregate_in_flight\x18\a \x01(\x04H\x01R\x11aggregateInFlight\x88\x01\x01\x12;\n" +
	"\n" +
	"capacities\x18\b \x03(\v2\x1b.hyperfaas.FunctionCapacityR\n" +
	"capacitiesB\f\n" +
	"\n" +
	"_leaf_loadB\x16\n" +
	"\x14_aggregate_in_flight2\xc2\x03\n" +
	"\x12LeafControlService\x12R\n" +
	"\rApplyFunction\x12\x1f.hyperfaas.ApplyFunctionRequest\x1a .hyperfaas.ApplyFunctionResponse\x12]\n" +
	"\x0eDeleteFunction\x12$.hyperfaas.DeleteLeafFunctionRequest\x1a%.hyperfaas.DeleteLeafFunctionResponse\x12U\n" +
	"\x0eEnsureCapacity\x12 .hyperfaas.EnsureCapacityRequest\x1a!.hyperfaas.EnsureCapacityResponse\x12H\n" +
	"\fCurrentState\x12\".hyperfaas.CurrentLeafStateRequest\x1a\x14.hyperfaas.LeafState\x12X\n" +
	"\x11WatchRoutingState\x12#.hyperfaas.WatchRoutingStateRequest\x1a\x1c.hyperfaas.RoutingStateFrame0\x01B\x1fZ\x1dhyperfaas-ideal-arch/pkg/leafb\x06proto3"

var (
	file_leaf_proto_rawDescOnce sync.Once
	file_leaf_proto_rawDescData []byte
)

func file_leaf_proto_rawDescGZIP() []byte {
	file_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaf_proto_rawDesc), len(file_leaf_proto_rawDesc)))
	})
	return file_leaf_proto_rawDescData
}

var file_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_leaf_proto_goTypes = []any{
	(*ApplyFunctionRequest)(nil),       // 0: hyperfaas.ApplyFunctionRequest
	(*ApplyFunctionResponse)(nil),      // 1: hyperfaas.ApplyFunctionResponse
	(*DeleteLeafFunctionRequest)(nil),  // 2: hyperfaas.DeleteLeafFunctionRequest
	(*DeleteLeafFunctionResponse)(nil), // 3: hyperfaas.DeleteLeafFunctionResponse
	(*EnsureCapacityRequest)(nil),      // 4: hyperfaas.EnsureCapacityRequest
	(*EnsureCapacityResponse)(nil),     // 5: hyperfaas.EnsureCapacityResponse
	(*CurrentLeafStateRequest)(nil),    // 6: hyperfaas.CurrentLeafStateRequest
	(*RoutingStateProjection)(nil),     // 7: hyperfaas.RoutingStateProjection
	(*WatchRoutingStateRequest)(nil),   // 8: hyperfaas.WatchRoutingStateRequest
	(*RoutingStateFrame)(nil),          // 9: hyperfaas.RoutingStateFrame
	(*core.FunctionSpec)(nil),          // 10: hyperfaas.FunctionSpec
	(*core.ScaleDemand)(nil),           // 11: hyperfaas.ScaleDemand
	(*core.FunctionCapacity)(nil),      // 12: hyperfaas.FunctionCapacity
	(*core.LeafState)(nil),             // 13: hyperfaas.LeafState
}
var file_leaf_proto_depIdxs = []int32{
	10, // 0: hyperfaas.ApplyFunctionRequest.function:type_name -> hyperfaas.FunctionSpec
	11, // 1: hyperfaas.EnsureCapacityRequest.demand:type_name -> hyperfaas.ScaleDemand
	7,  // 2: hyperfaas.WatchRoutingStateRequest.projection:type_name -> hyperfaas.RoutingStateProjection
	12, // 3: hyperfaas.RoutingStateFrame.capacities:type_name -> hyperfaas.FunctionCapacity
	0,  // 4: hyperfaas.LeafControlService.ApplyFunction:input_type -> hyperfaas.ApplyFunctionRequest
	2,  // 5: hyperfaas.LeafControlService.DeleteFunction:input_type -> hyperfaas.DeleteLeafFunctionRequest
	4,  // 6: hyperfaas.LeafControlService.EnsureCapacity:input_type -> hyperfaas.EnsureCapacityRequest
	6,  // 7: hyperfaas.LeafControlService.CurrentState:input_type -> hyperfaas.CurrentLeafStateRequest
	8,  // 8: hyperfaas.LeafControlService.WatchRoutingState:input_type -> hyperfaas.WatchRoutingStateRequest
	1,  // 9: hyperfaas.LeafControlService.ApplyFunction:output_type -> hyperfaas.ApplyFunctionResponse
	3,  // 10: hyperfaas.LeafControlService.DeleteFunction:output_type -> hyperfaas.DeleteLeafFunctionResponse
	5,  // 11: hyperfaas.LeafControlService.EnsureCapacity:output_type -> hyperfaas.EnsureCapacityResponse
	13, // 12: hyperfaas.LeafControlService.CurrentState:output_type -> hyperfaas.LeafState
	9,  // 13: hyperfaas.LeafControlService.WatchRoutingState:output_type -> hyperfaas.RoutingStateFrame
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_leaf_proto_init() }
func file_leaf_proto_init() {
	if File_leaf_proto != nil {
		return
	}
	file_leaf_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaf_proto_rawDesc), len(file_leaf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_proto_depIdxs,
		MessageInfos:      file_leaf_proto_msgTypes,
	}.Build()
	File_leaf_proto = out.File
	file_leaf_proto_goTypes = nil
	file_leaf_proto_depIdxs = nil
}
