// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: leaf.proto

package leaf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	core "hyperfaas-ideal-arch/pkg/core"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeafControlService_ApplyFunction_FullMethodName     = "/hyperfaas.LeafControlService/ApplyFunction"
	LeafControlService_DeleteFunction_FullMethodName    = "/hyperfaas.LeafControlService/DeleteFunction"
	LeafControlService_EnsureCapacity_FullMethodName    = "/hyperfaas.LeafControlService/EnsureCapacity"
	LeafControlService_CurrentState_FullMethodName      = "/hyperfaas.LeafControlService/CurrentState"
	LeafControlService_WatchRoutingState_FullMethodName = "/hyperfaas.LeafControlService/WatchRoutingState"
)

// LeafControlServiceClient is the client API for LeafControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeafControlServiceClient interface {
	ApplyFunction(ctx context.Context, in *ApplyFunctionRequest, opts ...grpc.CallOption) (*ApplyFunctionResponse, error)
	DeleteFunction(ctx context.Context, in *DeleteLeafFunctionRequest, opts ...grpc.CallOption) (*DeleteLeafFunctionResponse, error)
	// Used by the leaf autoscaler actuator, not by the invoke hot path.
	EnsureCapacity(ctx context.Context, in *EnsureCapacityRequest, opts ...grpc.CallOption) (*EnsureCapacityResponse, error)
	// Diagnostic full snapshot of one leaf. It is not used on the routing request
	// path; routing uses WatchRoutingState with an explicit projection.
	CurrentState(ctx context.Context, in *CurrentLeafStateRequest, opts ...grpc.CallOption) (*core.LeafState, error)
	// Streams routing state to one subscriber. The requested projection selects
	// which fields the leaf computes and sends, so a subscriber only pays for the
	// state it reads. The first frame is always a full snapshot for that
	// projection.
	WatchRoutingState(ctx context.Context, in *WatchRoutingStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingStateFrame], error)
}

type leafControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeafControlServiceClient(cc grpc.ClientConnInterface) LeafControlServiceClient {
	return &leafControlServiceClient{cc}
}

func (c *leafControlServiceClient) ApplyFunction(ctx context.Context, in *ApplyFunctionRequest, opts ...grpc.CallOption) (*ApplyFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyFunctionResponse)
	err := c.cc.Invoke(ctx, LeafControlService_ApplyFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafControlServiceClient) DeleteFunction(ctx context.Context, in *DeleteLeafFunctionRequest, opts ...grpc.CallOption) (*DeleteLeafFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLeafFunctionResponse)
	err := c.cc.Invoke(ctx, LeafControlService_DeleteFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafControlServiceClient) EnsureCapacity(ctx context.Context, in *EnsureCapacityRequest, opts ...grpc.CallOption) (*EnsureCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureCapacityResponse)
	err := c.cc.Invoke(ctx, LeafControlService_EnsureCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafControlServiceClient) CurrentState(ctx context.Context, in *CurrentLeafStateRequest, opts ...grpc.CallOption) (*core.LeafState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.LeafState)
	err := c.cc.Invoke(ctx, LeafControlService_CurrentState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafControlServiceClient) WatchRoutingState(ctx context.Context, in *WatchRoutingStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingStateFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeafControlService_ServiceDesc.Streams[0], LeafControlService_WatchRoutingState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRoutingStateRequest, RoutingStateFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeafControlService_WatchRoutingStateClient = grpc.ServerStreamingClient[RoutingStateFrame]

// LeafControlServiceServer is the server API for LeafControlService service.
// All implementations must embed UnimplementedLeafControlServiceServer
// for forward compatibility.
type LeafControlServiceServer interface {
	ApplyFunction(context.Context, *ApplyFunctionRequest) (*ApplyFunctionResponse, error)
	DeleteFunction(context.Context, *DeleteLeafFunctionRequest) (*DeleteLeafFunctionResponse, error)
	// Used by the leaf autoscaler actuator, not by the invoke hot path.
	EnsureCapacity(context.Context, *EnsureCapacityRequest) (*EnsureCapacityResponse, error)
	// Diagnostic full snapshot of one leaf. It is not used on the routing request
	// path; routing uses WatchRoutingState with an explicit projection.
	CurrentState(context.Context, *CurrentLeafStateRequest) (*core.LeafState, error)
	// Streams routing state to one subscriber. The requested projection selects
	// which fields the leaf computes and sends, so a subscriber only pays for the
	// state it reads. The first frame is always a full snapshot for that
	// projection.
	WatchRoutingState(*WatchRoutingStateRequest, grpc.ServerStreamingServer[RoutingStateFrame]) error
	mustEmbedUnimplementedLeafControlServiceServer()
}

// UnimplementedLeafControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeafControlServiceServer struct{}

func (UnimplementedLeafControlServiceServer) ApplyFunction(context.Context, *ApplyFunctionRequest) (*ApplyFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyFunction not implemented")
}
func (UnimplementedLeafControlServiceServer) DeleteFunction(context.Context, *DeleteLeafFunctionRequest) (*DeleteLeafFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFunction not implemented")
}
func (UnimplementedLeafControlServiceServer) EnsureCapacity(context.Context, *EnsureCapacityRequest) (*EnsureCapacityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureCapacity not implemented")
}
func (UnimplementedLeafControlServiceServer) CurrentState(context.Context, *CurrentLeafStateRequest) (*core.LeafState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentState not implemented")
}
func (UnimplementedLeafControlServiceServer) WatchRoutingState(*WatchRoutingStateRequest, grpc.ServerStreamingServer[RoutingStateFrame]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRoutingState not implemented")
}
func (UnimplementedLeafControlServiceServer) mustEmbedUnimplementedLeafControlServiceServer() {}
func (UnimplementedLeafControlServiceServer) testEmbeddedByValue()                            {}

// UnsafeLeafControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeafControlServiceServer will
// result in compilation errors.
type UnsafeLeafControlServiceServer interface {
	mustEmbedUnimplementedLeafControlServiceServer()
}

func RegisterLeafControlServiceServer(s grpc.ServiceRegistrar, srv LeafControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeafControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeafControlService_ServiceDesc, srv)
}

func _LeafControlService_ApplyFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafControlServiceServer).ApplyFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeafControlService_ApplyFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafControlServiceServer).ApplyFunction(ctx, req.(*ApplyFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafControlService_DeleteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLeafFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafControlServiceServer).DeleteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeafControlService_DeleteFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafControlServiceServer).DeleteFunction(ctx, req.(*DeleteLeafFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafControlService_EnsureCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafControlServiceServer).EnsureCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeafControlService_EnsureCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafControlServiceServer).EnsureCapacity(ctx, req.(*EnsureCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafControlService_CurrentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentLeafStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafControlServiceServer).CurrentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeafControlService_CurrentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafControlServiceServer).CurrentState(ctx, req.(*CurrentLeafStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafControlService_WatchRoutingState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRoutingStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeafControlServiceServer).WatchRoutingState(m, &grpc.GenericServerStream[WatchRoutingStateRequest, RoutingStateFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeafControlService_WatchRoutingStateServer = grpc.ServerStreamingServer[RoutingStateFrame]

// LeafControlService_ServiceDesc is the grpc.ServiceDesc for LeafControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeafControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperfaas.LeafControlService",
	HandlerType: (*LeafControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyFunction",
			Handler:    _LeafControlService_ApplyFunction_Handler,
		},
		{
			MethodName: "DeleteFunction",
			Handler:    _LeafControlService_DeleteFunction_Handler,
		},
		{
			MethodName: "EnsureCapacity",
			Handler:    _LeafControlService_EnsureCapacity_Handler,
		},
		{
			MethodName: "CurrentState",
			Handler:    _LeafControlService_CurrentState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRoutingState",
			Handler:       _LeafControlService_WatchRoutingState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "leaf.proto",
}
