# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\thyperfaas\")\n\x12SignalReadyRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\x04\"\x15\n\x13SignalReadyResponse2^\n\x0eSandboxService\x12L\n\x0bSignalReady\x12\x1d.hyperfaas.SignalReadyRequest\x1a\x1e.hyperfaas.SignalReadyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREADYREQUEST']._serialized_start=27
  _globals['_SIGNALREADYREQUEST']._serialized_end=68
  _globals['_SIGNALREADYRESPONSE']._serialized_start=70
  _globals['_SIGNALREADYRESPONSE']._serialized_end=91
  _globals['_SANDBOXSERVICE']._serialized_start=93
  _globals['_SANDBOXSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
