// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: worker/worker.proto

package worker

import (
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualizationType int32

const (
	VirtualizationType_CONTAINER VirtualizationType = 0
)

// Enum value maps for VirtualizationType.
var (
	VirtualizationType_name = map[int32]string{
		0: "CONTAINER",
	}
	VirtualizationType_value = map[string]int32{
		"CONTAINER": 0,
	}
)

func (x VirtualizationType) Enum() *VirtualizationType {
	p := new(VirtualizationType)
	*p = x
	return p
}

func (x VirtualizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_worker_proto_enumTypes[0].Descriptor()
}

func (VirtualizationType) Type() protoreflect.EnumType {
	return &file_worker_worker_proto_enumTypes[0]
}

func (x VirtualizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualizationType.Descriptor instead.
func (VirtualizationType) EnumDescriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{0}
}

type Event int32

const (
	Event_EVENT_RESPONSE_UNSPECIFIED Event = 0
	Event_EVENT_DOWN                 Event = 1
	Event_EVENT_TIMEOUT              Event = 2
	Event_EVENT_START                Event = 3
	Event_EVENT_STOP                 Event = 4
	Event_EVENT_CALL                 Event = 5
	Event_EVENT_RUNNING              Event = 6
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "EVENT_RESPONSE_UNSPECIFIED",
		1: "EVENT_DOWN",
		2: "EVENT_TIMEOUT",
		3: "EVENT_START",
		4: "EVENT_STOP",
		5: "EVENT_CALL",
		6: "EVENT_RUNNING",
	}
	Event_value = map[string]int32{
		"EVENT_RESPONSE_UNSPECIFIED": 0,
		"EVENT_DOWN":                 1,
		"EVENT_TIMEOUT":              2,
		"EVENT_START":                3,
		"EVENT_STOP":                 4,
		"EVENT_CALL":                 5,
		"EVENT_RUNNING":              6,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_worker_proto_enumTypes[1].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_worker_worker_proto_enumTypes[1]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_STATUS_SUCCESS_UNSPECIFIED Status = 0
	Status_STATUS_FAILED              Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_SUCCESS_UNSPECIFIED",
		1: "STATUS_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_SUCCESS_UNSPECIFIED": 0,
		"STATUS_FAILED":              1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_worker_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_worker_worker_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{2}
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Type          VirtualizationType     `protobuf:"varint,2,opt,name=type,proto3,enum=worker.VirtualizationType" json:"type,omitempty"`
	Event         Event                  `protobuf:"varint,3,opt,name=event,proto3,enum=worker.Event" json:"event,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=worker.Status" json:"status,omitempty"`
	FunctionId    string                 `protobuf:"bytes,5,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *StatusUpdate) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StatusUpdate) GetType() VirtualizationType {
	if x != nil {
		return x.Type
	}
	return VirtualizationType_CONTAINER
}

func (x *StatusUpdate) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_EVENT_RESPONSE_UNSPECIFIED
}

func (x *StatusUpdate) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_SUCCESS_UNSPECIFIED
}

func (x *StatusUpdate) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *StatusUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type MetricsUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UsedRamPercent    float64                `protobuf:"fixed64,1,opt,name=used_ram_percent,json=usedRamPercent,proto3" json:"used_ram_percent,omitempty"`
	CpuPercentPercpus []float64              `protobuf:"fixed64,2,rep,packed,name=cpu_percent_percpus,json=cpuPercentPercpus,proto3" json:"cpu_percent_percpus,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsUpdate) Reset() {
	*x = MetricsUpdate{}
	mi := &file_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUpdate) ProtoMessage() {}

func (x *MetricsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUpdate.ProtoReflect.Descriptor instead.
func (*MetricsUpdate) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsUpdate) GetUsedRamPercent() float64 {
	if x != nil {
		return x.UsedRamPercent
	}
	return 0
}

func (x *MetricsUpdate) GetCpuPercentPercpus() []float64 {
	if x != nil {
		return x.CpuPercentPercpus
	}
	return nil
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceIp    string                 `protobuf:"bytes,2,opt,name=instance_ip,json=instanceIp,proto3" json:"instance_ip,omitempty"`
	InstanceName  string                 `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_worker_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StartResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartResponse) GetInstanceIp() string {
	if x != nil {
		return x.InstanceIp
	}
	return ""
}

func (x *StartResponse) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_worker_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{5}
}

func (x *StartRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_worker_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_worker_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type SignalReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalReadyRequest) Reset() {
	*x = SignalReadyRequest{}
	mi := &file_worker_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalReadyRequest) ProtoMessage() {}

func (x *SignalReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalReadyRequest.ProtoReflect.Descriptor instead.
func (*SignalReadyRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{8}
}

func (x *SignalReadyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_worker_worker_proto protoreflect.FileDescriptor

const file_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x13worker/worker.proto\x12\x06worker\x1a\x13common/common.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x02\n" +
	"\fStatusUpdate\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.worker.VirtualizationTypeR\x04type\x12#\n" +
	"\x05event\x18\x03 \x01(\x0e2\r.worker.EventR\x05event\x12&\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0e.worker.StatusR\x06status\x12\x1f\n" +
	"\vfunction_id\x18\x05 \x01(\tR\n" +
	"functionId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\")\n" +
	"\x0eMetricsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"i\n" +
	"\rMetricsUpdate\x12(\n" +
	"\x10used_ram_percent\x18\x01 \x01(\x01R\x0eusedRamPercent\x12.\n" +
	"\x13cpu_percent_percpus\x18\x02 \x03(\x01R\x11cpuPercentPercpus\"v\n" +
	"\rStartResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vinstance_ip\x18\x02 \x01(\tR\n" +
	"instanceIp\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\"/\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\".\n" +
	"\vStopRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"/\n" +
	"\fStopResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"5\n" +
	"\x12SignalReadyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId*#\n" +
	"\x12VirtualizationType\x12\r\n" +
	"\tCONTAINER\x10\x00*\x8e\x01\n" +
	"\x05Event\x12\x1e\n" +
	"\x1aEVENT_RESPONSE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"EVENT_DOWN\x10\x01\x12\x11\n" +
	"\rEVENT_TIMEOUT\x10\x02\x12\x0f\n" +
	"\vEVENT_START\x10\x03\x12\x0e\n" +
	"\n" +
	"EVENT_STOP\x10\x04\x12\x0e\n" +
	"\n" +
	"EVENT_CALL\x10\x05\x12\x11\n" +
	"\rEVENT_RUNNING\x10\x06*;\n" +
	"\x06Status\x12\x1e\n" +
	"\x1aSTATUS_SUCCESS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x012\xda\x02\n" +
	"\x06Worker\x124\n" +
	"\x05Start\x12\x14.worker.StartRequest\x1a\x15.worker.StartResponse\x121\n" +
	"\x04Call\x12\x13.common.CallRequest\x1a\x14.common.CallResponse\x121\n" +
	"\x04Stop\x12\x13.worker.StopRequest\x1a\x14.worker.StopResponse\x127\n" +
	"\x06Status\x12\x15.worker.StatusRequest\x1a\x14.worker.StatusUpdate0\x01\x128\n" +
	"\aMetrics\x12\x16.worker.MetricsRequest\x1a\x15.worker.MetricsUpdate\x12A\n" +
	"\vSignalReady\x12\x1a.worker.SignalReadyRequest\x1a\x16.google.protobuf.EmptyB/Z-github.com/3s-rg-codes/HyperFaaS/proto/workerb\x06proto3"

var (
	file_worker_worker_proto_rawDescOnce sync.Once
	file_worker_worker_proto_rawDescData []byte
)

func file_worker_worker_proto_rawDescGZIP() []byte {
	file_worker_worker_proto_rawDescOnce.Do(func() {
		file_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_worker_proto_rawDesc), len(file_worker_worker_proto_rawDesc)))
	})
	return file_worker_worker_proto_rawDescData
}

var file_worker_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_worker_worker_proto_goTypes = []any{
	(VirtualizationType)(0),       // 0: worker.VirtualizationType
	(Event)(0),                    // 1: worker.Event
	(Status)(0),                   // 2: worker.Status
	(*StatusUpdate)(nil),          // 3: worker.StatusUpdate
	(*StatusRequest)(nil),         // 4: worker.StatusRequest
	(*MetricsRequest)(nil),        // 5: worker.MetricsRequest
	(*MetricsUpdate)(nil),         // 6: worker.MetricsUpdate
	(*StartResponse)(nil),         // 7: worker.StartResponse
	(*StartRequest)(nil),          // 8: worker.StartRequest
	(*StopRequest)(nil),           // 9: worker.StopRequest
	(*StopResponse)(nil),          // 10: worker.StopResponse
	(*SignalReadyRequest)(nil),    // 11: worker.SignalReadyRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*common.CallRequest)(nil),    // 13: common.CallRequest
	(*common.CallResponse)(nil),   // 14: common.CallResponse
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_worker_worker_proto_depIdxs = []int32{
	0,  // 0: worker.StatusUpdate.type:type_name -> worker.VirtualizationType
	1,  // 1: worker.StatusUpdate.event:type_name -> worker.Event
	2,  // 2: worker.StatusUpdate.status:type_name -> worker.Status
	12, // 3: worker.StatusUpdate.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 4: worker.Worker.Start:input_type -> worker.StartRequest
	13, // 5: worker.Worker.Call:input_type -> common.CallRequest
	9,  // 6: worker.Worker.Stop:input_type -> worker.StopRequest
	4,  // 7: worker.Worker.Status:input_type -> worker.StatusRequest
	5,  // 8: worker.Worker.Metrics:input_type -> worker.MetricsRequest
	11, // 9: worker.Worker.SignalReady:input_type -> worker.SignalReadyRequest
	7,  // 10: worker.Worker.Start:output_type -> worker.StartResponse
	14, // 11: worker.Worker.Call:output_type -> common.CallResponse
	10, // 12: worker.Worker.Stop:output_type -> worker.StopResponse
	3,  // 13: worker.Worker.Status:output_type -> worker.StatusUpdate
	6,  // 14: worker.Worker.Metrics:output_type -> worker.MetricsUpdate
	15, // 15: worker.Worker.SignalReady:output_type -> google.protobuf.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_worker_worker_proto_init() }
func file_worker_worker_proto_init() {
	if File_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_worker_proto_rawDesc), len(file_worker_worker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_worker_proto_goTypes,
		DependencyIndexes: file_worker_worker_proto_depIdxs,
		EnumInfos:         file_worker_worker_proto_enumTypes,
		MessageInfos:      file_worker_worker_proto_msgTypes,
	}.Build()
	File_worker_worker_proto = out.File
	file_worker_worker_proto_goTypes = nil
	file_worker_worker_proto_depIdxs = nil
}
