// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: function/function.proto

package hyperfaas

import (
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_function_function_proto protoreflect.FileDescriptor

const file_function_function_proto_rawDesc = "" +
	"\n" +
	"\x17function/function.proto\x12\bfunction\x1a\x13common/common.proto2D\n" +
	"\x0fFunctionService\x121\n" +
	"\x04Call\x12\x13.common.CallRequest\x1a\x14.common.CallResponseB\"Z github.com/3s-rg-codes/hyperfaasb\x06proto3"

var file_function_function_proto_goTypes = []any{
	(*common.CallRequest)(nil),  // 0: common.CallRequest
	(*common.CallResponse)(nil), // 1: common.CallResponse
}
var file_function_function_proto_depIdxs = []int32{
	0, // 0: function.FunctionService.Call:input_type -> common.CallRequest
	1, // 1: function.FunctionService.Call:output_type -> common.CallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_function_function_proto_init() }
func file_function_function_proto_init() {
	if File_function_function_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_function_function_proto_rawDesc), len(file_function_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_function_function_proto_goTypes,
		DependencyIndexes: file_function_function_proto_depIdxs,
	}.Build()
	File_function_function_proto = out.File
	file_function_function_proto_goTypes = nil
	file_function_function_proto_depIdxs = nil
}
