"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Payload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    FIRSTEXECUTION_FIELD_NUMBER: builtins.int
    data: builtins.str
    id: builtins.str
    firstExecution: builtins.bool
    def __init__(
        self,
        *,
        data: builtins.str = ...,
        id: builtins.str = ...,
        firstExecution: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "firstExecution", b"firstExecution", "id", b"id"]) -> None: ...

global___Payload = Payload

@typing.final
class Call(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    data: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        data: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "id", b"id"]) -> None: ...

global___Call = Call
