# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66unction.proto\x12\x08\x66unction\";\n\x07Payload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x16\n\x0e\x66irstExecution\x18\x03 \x01(\x08\" \n\x04\x43\x61ll\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2=\n\x0f\x46unctionService\x12*\n\x05Ready\x12\x11.function.Payload\x1a\x0e.function.CallB\"Z github.com/3s-rg-codes/hyperfaasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/3s-rg-codes/hyperfaas'
  _globals['_PAYLOAD']._serialized_start=28
  _globals['_PAYLOAD']._serialized_end=87
  _globals['_CALL']._serialized_start=89
  _globals['_CALL']._serialized_end=121
  _globals['_FUNCTIONSERVICE']._serialized_start=123
  _globals['_FUNCTIONSERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
