// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: lb/lb.proto

package lb

import (
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_lb_lb_proto protoreflect.FileDescriptor

const file_lb_lb_proto_rawDesc = "" +
	"\n" +
	"\vlb/lb.proto\x12\x02lb\x1a\x13common/common.proto2\x90\x01\n" +
	"\x02LB\x129\n" +
	"\fScheduleCall\x12\x13.common.CallRequest\x1a\x14.common.CallResponse\x12O\n" +
	"\x0eCreateFunction\x12\x1d.common.CreateFunctionRequest\x1a\x1e.common.CreateFunctionResponseB+Z)github.com/3s-rg-codes/HyperFaaS/proto/lbb\x06proto3"

var file_lb_lb_proto_goTypes = []any{
	(*common.CallRequest)(nil),            // 0: common.CallRequest
	(*common.CreateFunctionRequest)(nil),  // 1: common.CreateFunctionRequest
	(*common.CallResponse)(nil),           // 2: common.CallResponse
	(*common.CreateFunctionResponse)(nil), // 3: common.CreateFunctionResponse
}
var file_lb_lb_proto_depIdxs = []int32{
	0, // 0: lb.LB.ScheduleCall:input_type -> common.CallRequest
	1, // 1: lb.LB.CreateFunction:input_type -> common.CreateFunctionRequest
	2, // 2: lb.LB.ScheduleCall:output_type -> common.CallResponse
	3, // 3: lb.LB.CreateFunction:output_type -> common.CreateFunctionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lb_lb_proto_init() }
func file_lb_lb_proto_init() {
	if File_lb_lb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lb_lb_proto_rawDesc), len(file_lb_lb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lb_lb_proto_goTypes,
		DependencyIndexes: file_lb_lb_proto_depIdxs,
	}.Build()
	File_lb_lb_proto = out.File
	file_lb_lb_proto_goTypes = nil
	file_lb_lb_proto_depIdxs = nil
}
