// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: lb/lb.proto

package lb

import (
	context "context"
	common "github.com/3s-rg-codes/HyperFaaS/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LB_ScheduleCall_FullMethodName = "/lb.LB/ScheduleCall"
)

// LBClient is the client API for LB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LBClient interface {
	// Sends a call request down the load balancing chain
	ScheduleCall(ctx context.Context, in *common.CallRequest, opts ...grpc.CallOption) (*common.CallResponse, error)
}

type lBClient struct {
	cc grpc.ClientConnInterface
}

func NewLBClient(cc grpc.ClientConnInterface) LBClient {
	return &lBClient{cc}
}

func (c *lBClient) ScheduleCall(ctx context.Context, in *common.CallRequest, opts ...grpc.CallOption) (*common.CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CallResponse)
	err := c.cc.Invoke(ctx, LB_ScheduleCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LBServer is the server API for LB service.
// All implementations must embed UnimplementedLBServer
// for forward compatibility.
type LBServer interface {
	// Sends a call request down the load balancing chain
	ScheduleCall(context.Context, *common.CallRequest) (*common.CallResponse, error)
	mustEmbedUnimplementedLBServer()
}

// UnimplementedLBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLBServer struct{}

func (UnimplementedLBServer) ScheduleCall(context.Context, *common.CallRequest) (*common.CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleCall not implemented")
}
func (UnimplementedLBServer) mustEmbedUnimplementedLBServer() {}
func (UnimplementedLBServer) testEmbeddedByValue()            {}

// UnsafeLBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LBServer will
// result in compilation errors.
type UnsafeLBServer interface {
	mustEmbedUnimplementedLBServer()
}

func RegisterLBServer(s grpc.ServiceRegistrar, srv LBServer) {
	// If the following call pancis, it indicates UnimplementedLBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LB_ServiceDesc, srv)
}

func _LB_ScheduleCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LBServer).ScheduleCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LB_ScheduleCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LBServer).ScheduleCall(ctx, req.(*common.CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LB_ServiceDesc is the grpc.ServiceDesc for LB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lb.LB",
	HandlerType: (*LBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleCall",
			Handler:    _LB_ScheduleCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lb/lb.proto",
}
