# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import common_pb2 as common_dot_common__pb2
from controller import controller_pb2 as controller_dot_controller__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in controller/controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/controller.Controller/Start',
                request_serializer=common_dot_common__pb2.FunctionID.SerializeToString,
                response_deserializer=controller_dot_controller__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Call = channel.unary_unary(
                '/controller.Controller/Call',
                request_serializer=common_dot_common__pb2.CallRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.CallResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/controller.Controller/Stop',
                request_serializer=common_dot_common__pb2.InstanceID.SerializeToString,
                response_deserializer=common_dot_common__pb2.InstanceID.FromString,
                _registered_method=True)
        self.Status = channel.unary_stream(
                '/controller.Controller/Status',
                request_serializer=controller_dot_controller__pb2.StatusRequest.SerializeToString,
                response_deserializer=controller_dot_controller__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/controller.Controller/Metrics',
                request_serializer=controller_dot_controller__pb2.MetricsRequest.SerializeToString,
                response_deserializer=controller_dot_controller__pb2.MetricsUpdate.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """rpc InstanceState (InstanceStateRequest) returns (InstanceStateResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=common_dot_common__pb2.FunctionID.FromString,
                    response_serializer=controller_dot_controller__pb2.StartResponse.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=common_dot_common__pb2.CallRequest.FromString,
                    response_serializer=common_dot_common__pb2.CallResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=common_dot_common__pb2.InstanceID.FromString,
                    response_serializer=common_dot_common__pb2.InstanceID.SerializeToString,
            ),
            'Status': grpc.unary_stream_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=controller_dot_controller__pb2.StatusRequest.FromString,
                    response_serializer=controller_dot_controller__pb2.StatusUpdate.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=controller_dot_controller__pb2.MetricsRequest.FromString,
                    response_serializer=controller_dot_controller__pb2.MetricsUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controller.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/Start',
            common_dot_common__pb2.FunctionID.SerializeToString,
            controller_dot_controller__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/Call',
            common_dot_common__pb2.CallRequest.SerializeToString,
            common_dot_common__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/Stop',
            common_dot_common__pb2.InstanceID.SerializeToString,
            common_dot_common__pb2.InstanceID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/controller.Controller/Status',
            controller_dot_controller__pb2.StatusRequest.SerializeToString,
            controller_dot_controller__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/Metrics',
            controller_dot_controller__pb2.MetricsRequest.SerializeToString,
            controller_dot_controller__pb2.MetricsUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
